<a href="https://colab.research.google.com/github/alperyldzzz/Lab/blob/main/Lab6-Exercise4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.linalg


def LU_partial_decomposition(A):
    A = A.copy()
    n = len(A)

    P = np.eye(n)
    L = np.zeros((n, n))
    U = A.copy()

    for k in range(n):
        # Pivoting
        pivot = np.argmax(abs(U[k:n, k])) + k

        if pivot != k:
            U[[k, pivot]] = U[[pivot, k]]
            P[[k, pivot]] = P[[pivot, k]]

            if k > 0:
                L[[k, pivot], :k] = L[[pivot, k], :k]

        # Elimination
        for i in range(k + 1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] = U[i, k:] - L[i, k] * U[k, k:]

    for i in range(n):
        L[i, i] = 1

    return P, L, U


A = np.array([
    [1, 2, 1],
    [1, -2, 2],
    [2, 12, -2]
], dtype=float)

b = np.array([0, 4, 4], dtype=float)

P, L, U = LU_partial_decomposition(A)

# Since P*A = L*U, first calculate P*b
b_pivoted = P @ b

# Solve L*y = P*b
y = scipy.linalg.solve_triangular(L, b_pivoted, lower=True)

# Solve U*x = y
x = scipy.linalg.solve_triangular(U, y)

x_check = scipy.linalg.solve(A, b)

print("Exercise 4 - LU Decomposition with Pivoting")
print("------------------------------------------")

print("P matrix:")
print(P)

print("\nL matrix:")
print(L)

print("\nU matrix:")
print(U)

print("\nSolution using LU decomposition:")
print(x)

print("\nCheck using scipy.linalg.solve:")
print(x_check)

Exercise 4 - LU Decomposition with Pivoting
------------------------------------------
P matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

L matrix:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]]

U matrix:
[[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]

Solution using LU decomposition:
[11.  -2.5 -6. ]

Check using scipy.linalg.solve:
[11.  -2.5 -6. ]
